#
# Copyright (c) 2009-2012 Joshua Hughes <kivhift@gmail.com>
#
import pu.scons.utils as su
import pu.scons.pyqt4 as squ

Import('env')

e = env.Clone()

qmk = e.SharedLibrary(source = ['qmk-hook.c'], no_import_lib = 1)
e.AddPostAction(qmk, e['strip_all'])
su.carefully_install(e, '#src', qmk)

squ.setup_pyqt4_builders(e, Builder)

qrc = squ.pyrcc4(e, 'qmk-resources.qrc')
e.AddPostAction([qrc], su.decrlf)
su.carefully_install(e, '#src', qrc)

# vim: filetype=python
